%
%  test_uicomponent.m
%
%  Created by Léa Strobino.
%  Copyright 2015. All rights reserved.
%

classdef test_uicomponent < handle
  
  properties % (Access = private)
    h
    s
    d
  end
  
  methods
    
    function this = test_uicomponent()
      
      % Default data
      this.d.appdir = [fileparts(mfilename('fullpath')) filesep];
      this.d.path = UIComponent.getUserDirectory();
      img = imread([matlabroot '/resources/coreui/matlab/splash.png']);
      icon = UIComponent.createIcon(imresize(img,[200 200]));
      
      % Main window
      this.h.window = UIComponent.Figure(...
        'CloseRequestFcn',@this.closeRequestFcn,...
        'Name','UIComponent class',...
        'Size',[240 710],...
        'WindowKeyPressFcn',@this.keyPressedFcn);
      
      this.h.panel = UIComponent.Panel(...
        'Parent',this.h.window,...
        'Position',[10 11 223 697],...
        'Title','Panel');
      
      this.h.label = UIComponent.Label(...
        'HorizontalAlignment','left',...
        'Parent',this.h.panel,...
        'Position',[10 10 200 20],...
        'String','javax.swing.JLabel');
      
      this.h.spinner = UIComponent.Spinner(...
        'Callback',{@this.callbackFcn,'Spinner value: %d','Value'},...
        'Parent',this.h.panel,...
        'Position',[10 40 100 24],...
        'Value',5);
      
      this.h.button = UIComponent.Button(...
        'Callback',{@this.callbackFcn,'Button label: %s','String'},...
        'Parent',this.h.panel,...
        'Position',[120 40 90 24],...
        'String','JButton');
      
      this.h.textfield = UIComponent.TextField(...
        'Callback',{@this.callbackFcn,'TextField contents: %s','Value'},...
        'HorizontalAlignment','left',...
        'Parent',this.h.panel,...
        'Position',[10 80 200 30],...
        'Value','JTextField');
      
      this.h.progressbar = UIComponent.ProgressBar(...
        'Parent',this.h.panel,...
        'Position',[10 120 200 20],...
        'Value',.45);
      
      this.h.slider = UIComponent.Slider(...
        'Callback',@this.sliderFcn,...
        'Max',1000,...
        'Min',0,...
        'Parent',this.h.panel,...
        'Position',[10 150 200 20],...
        'Value',300);
      
      this.h.checkbox = UIComponent.CheckBox(...
        'Callback',{@this.callbackFcn,'CheckBox value: %d','Value'},...
        'Parent',this.h.panel,...
        'Position',[60 180 100 20],...
        'String','JCheckBox',...
        'Value',1);
      
      this.h.radiobuttongroup = UIComponent.RadioButtonGroup(...
        'Callback',@(~,~,e)fprintf('RadioButton selected: #%d\n',e.NewValue),...
        'Parent',this.h.panel,...
        'Position',[10 210 200 20]);
      
      this.h.radiobutton(1) = UIComponent.RadioButton(...
        'Parent',this.h.radiobuttongroup,...
        'Position',[0 0 100 20],...
        'String','Radio #1');
      
      this.h.radiobutton(2) = UIComponent.RadioButton(...
        'Parent',this.h.radiobuttongroup,...
        'Position',[100 0 100 20],...
        'String','Radio #2');
      
      this.h.combobox = UIComponent.ComboBox(...
        'Callback',{@this.callbackFcn,'ComboBox item selected: #%d','Value'},...
        'Parent',this.h.panel,...
        'Position',[35 240 150 24],...
        'String',{'JComboBox 1','JComboBox 2','JComboBox 3'});
      
      this.h.dial = UIComponent.Dial(...
        'IndicatorNumberFormat','0.0%',...
        'Parent',this.h.panel,...
        'Position',[20 280 180 180],...
        'Max',1-1/360,...
        'MajorTickSpacing',.1,...
        'Min',0,...
        'MinorTickSpacing',.02,...
        'NumberFormat','0%',...
        'StartAngle',450,...
        'StopAngle',91);
      
      this.h.icon = UIComponent.Label(...
        'Icon',icon,...
        'Parent',this.h.panel,...
        'Position',[10 473 200 200]);
      
      % Timer
      this.h.timer = timer(...
        'Name',[mfilename '::requestFocus'],...
        'TimerFcn',@this.requestFocus,...
        'StartDelay',3);
      
      this.h.jframe = UIComponent.getJFrame(this.h.window);
      
    end
    
  end
  
  methods (Access = private)
    
    function closeRequestFcn(this,~,~)
      try %#ok<TRYNC>
        this.h.window.Visible = 'off';
      end
      stop(this.h.timer);
      delete(this.h.timer);
      close(this.h.window,'force');
    end
    
    function callbackFcn(this,object,string,property)
      stop(this.h.timer);
      fprintf([string '\n'],object.(property));
      start(this.h.timer);
    end
    
    function keyPressedFcn(~,~,k)
      if k.Key == '0'
        k = k.Character;
      else
        k = k.Key;
      end
      fprintf('Key pressed: %s\n',k);
    end
    
    function requestFocus(this,~,~)
      this.h.jframe.requestFocus();
    end
    
    function sliderFcn(this,object)
      stop(this.h.timer);
      v = 1E-3*object.Value;
      this.h.progressbar.Value = v;
      this.h.dial.Value = v;
      start(this.h.timer);
    end
    
  end
  
end
